version: 2

models:
  - name: customer_orders
    tests:
      - dbt_utils.unique_combination_of_columns:
         combination_of_columns:
           - customer_id
           - order_id
    columns: 
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stage_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stage_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values: ['created', 'shipped', 'approved', 'canceled', 'invoiced', 'delivered', 'processing', 'unavailable']